backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
