package com.oms.orderservice.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.oms.orderservice.api.dto.CreateOrderRequest;
import com.oms.orderservice.api.dto.OrderItemRequest;
import com.oms.orderservice.application.OrderCommandService;
import com.oms.orderservice.domain.model.Order;
import com.oms.orderservice.domain.model.OrderItem;
import com.oms.orderservice.domain.model.OrderStatus;
import com.oms.orderservice.infrastructure.idempotency.IdempotencyResult;
import com.oms.orderservice.infrastructure.idempotency.IdempotencyService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(OrderController.class)
class OrderControllerTest {

        @Autowired
        private MockMvc mockMvc;

        @MockBean
        private OrderCommandService orderCommandService;

        @MockBean
        private IdempotencyService idempotencyService;

        @Autowired
        private ObjectMapper objectMapper;

        @Test
        void shouldCreateOrderEndpoint() throws Exception {
                // Given
                String idempotencyKey = "key-123";

                OrderItemRequest itemReq = new OrderItemRequest();
                itemReq.setProductId("prod-1");
                itemReq.setQuantity(1);
                itemReq.setPrice(BigDecimal.valueOf(100));

                CreateOrderRequest request = new CreateOrderRequest();
                request.setItems(List.of(itemReq));

                when(idempotencyService.tryAcquire(idempotencyKey))
                                .thenReturn(IdempotencyResult.acquired());

                // Mock return value using factory
                Order createdOrder = Order.create(List.of(OrderItem.create("prod-1", 1, BigDecimal.valueOf(100))));
                // Reflection to set ID if needed since it is generated by JPA?
                // Creating order via factory should be enough, ID might be null unless we mock
                // specific behavior or use reflection to set it,
                // but OrderController likely returns what the service returns.
                // However, without an ID, the controller might fail if it tries to return it.
                // Let's rely on the service returning the object where we can potentially
                // inspect fields.
                // Actually, since ID is generated by DB usually, and create() doesn't set it,
                // it will be null unless saved.
                // Since we mock the command service, we can stub the return.
                // But Order.id has no setter. We probably don't need ID for strict equality
                // check if we just check status.
                // If the controller returns ID, it will be null.

                when(orderCommandService.createOrder(any())).thenReturn(createdOrder);

                // When/Then
                mockMvc.perform(post("/orders")
                                .header("Idempotency-Key", idempotencyKey)
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(request)))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.status").value("PENDING"));

                verify(idempotencyService).markCompleted(eq(idempotencyKey), any(), any());
        }

        @Test
        void shouldReturnConflictWhenInProgress() throws Exception {
                String idempotencyKey = "key-123";
                when(idempotencyService.tryAcquire(idempotencyKey))
                                .thenReturn(IdempotencyResult.inProgress());

                OrderItemRequest itemReq = new OrderItemRequest();
                itemReq.setProductId("prod-1");
                itemReq.setQuantity(1);
                itemReq.setPrice(BigDecimal.valueOf(100));

                CreateOrderRequest request = new CreateOrderRequest();
                request.setItems(List.of(itemReq));

                mockMvc.perform(post("/orders")
                                .header("Idempotency-Key", idempotencyKey)
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(request)))
                                .andExpect(status().isConflict());
        }
}
